-- ==========================================
-- 팔로우 시스템 추가
-- ==========================================

-- 1. follows 테이블 생성
CREATE TABLE IF NOT EXISTS follows (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    following_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(follower_id, following_id),
    CHECK (follower_id != following_id)
);

-- 인덱스 생성 (성능 최적화)
CREATE INDEX IF NOT EXISTS follows_follower_id_idx ON follows(follower_id);
CREATE INDEX IF NOT EXISTS follows_following_id_idx ON follows(following_id);

-- 2. RLS 활성화
ALTER TABLE follows ENABLE ROW LEVEL SECURITY;

-- 3. 보안 정책
DROP POLICY IF EXISTS "Anyone can read follows" ON follows;
CREATE POLICY "Anyone can read follows" ON follows FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can follow" ON follows;
CREATE POLICY "Authenticated users can follow" ON follows
    FOR INSERT WITH CHECK (auth.uid() = follower_id);

DROP POLICY IF EXISTS "Users can unfollow" ON follows;
CREATE POLICY "Users can unfollow" ON follows
    FOR DELETE USING (auth.uid() = follower_id);

-- 4. profiles 테이블에 팔로워/팔로잉 수 컬럼 추가 (선택사항, 성능 최적화용)
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS followers_count INT DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS following_count INT DEFAULT 0;

-- 5. 팔로우 수 자동 업데이트 함수
CREATE OR REPLACE FUNCTION update_follow_counts()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        -- 팔로잉 수 증가
        UPDATE profiles SET following_count = following_count + 1 
        WHERE user_id = NEW.follower_id;
        -- 팔로워 수 증가
        UPDATE profiles SET followers_count = followers_count + 1 
        WHERE user_id = NEW.following_id;
    ELSIF TG_OP = 'DELETE' THEN
        -- 팔로잉 수 감소
        UPDATE profiles SET following_count = following_count - 1 
        WHERE user_id = OLD.follower_id;
        -- 팔로워 수 감소
        UPDATE profiles SET followers_count = followers_count - 1 
        WHERE user_id = OLD.following_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

-- 6. 트리거 생성
DROP TRIGGER IF EXISTS update_follow_counts_trigger ON follows;
CREATE TRIGGER update_follow_counts_trigger
    AFTER INSERT OR DELETE ON follows
    FOR EACH ROW EXECUTE FUNCTION update_follow_counts();

-- 7. 기존 데이터 팔로우 수 초기화
UPDATE profiles SET 
    followers_count = (SELECT COUNT(*) FROM follows WHERE following_id = profiles.user_id),
    following_count = (SELECT COUNT(*) FROM follows WHERE follower_id = profiles.user_id);

-- ==========================================
-- 완료!
-- ==========================================
