-- ==========================================
-- 🚀 Supabase 데이터베이스 전체 설정
-- ==========================================
-- 
-- 📋 사용 방법:
-- 1. Supabase 대시보드 접속
-- 2. 왼쪽 메뉴에서 "SQL Editor" 클릭
-- 3. 이 파일의 전체 내용을 복사하여 붙여넣기
-- 4. "Run" 버튼 클릭
-- 
-- ⚠️ 주의: 이미 테이블이 있어도 안전하게 실행됩니다 (IF NOT EXISTS 사용)
-- ==========================================

-- ==========================================
-- 1️⃣ posts 테이블 (게시물)
-- ==========================================
CREATE TABLE IF NOT EXISTS posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    author_email TEXT NOT NULL,
    author_nickname TEXT,
    user_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- author_nickname 컬럼 추가 (이미 있으면 무시)
ALTER TABLE posts ADD COLUMN IF NOT EXISTS author_nickname TEXT;

-- ==========================================
-- 2️⃣ comments 테이블 (댓글)
-- ==========================================
CREATE TABLE IF NOT EXISTS comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    author_email TEXT NOT NULL,
    author_nickname TEXT,
    user_id UUID NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- author_nickname 컬럼 추가 (이미 있으면 무시)
ALTER TABLE comments ADD COLUMN IF NOT EXISTS author_nickname TEXT;

-- ==========================================
-- 3️⃣ profiles 테이블 (사용자 프로필)
-- ==========================================
-- 기존 profiles 테이블 삭제 후 재생성 (⚠️ 주의: 기존 데이터 삭제됨)
DROP TABLE IF EXISTS profiles CASCADE;

-- profiles 테이블 생성
CREATE TABLE profiles (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    nickname TEXT NOT NULL DEFAULT '',
    bio TEXT DEFAULT '',
    avatar_url TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- user_id에 인덱스 생성 (빠른 조회)
CREATE INDEX profiles_user_id_idx ON profiles(user_id);

-- 테이블 소유자를 postgres로 설정
ALTER TABLE profiles OWNER TO postgres;

-- ==========================================
-- 4️⃣ RLS (Row Level Security) 활성화
-- ==========================================
ALTER TABLE posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 5️⃣ posts 테이블 보안 정책
-- ==========================================
-- 기존 정책 삭제 후 재생성
DROP POLICY IF EXISTS "Anyone can read posts" ON posts;
CREATE POLICY "Anyone can read posts" ON posts FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create posts" ON posts;
CREATE POLICY "Authenticated users can create posts" ON posts
    FOR INSERT WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can update own posts" ON posts;
CREATE POLICY "Users can update own posts" ON posts
    FOR UPDATE USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Users can delete own posts" ON posts;
CREATE POLICY "Users can delete own posts" ON posts
    FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 6️⃣ comments 테이블 보안 정책
-- ==========================================
DROP POLICY IF EXISTS "Anyone can read comments" ON comments;
CREATE POLICY "Anyone can read comments" ON comments FOR SELECT USING (true);

DROP POLICY IF EXISTS "Authenticated users can create comments" ON comments;
CREATE POLICY "Authenticated users can create comments" ON comments 
    FOR INSERT WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Users can delete comments" ON comments;
CREATE POLICY "Users can delete comments" ON comments 
    FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 7️⃣ profiles 테이블 보안 정책
-- ==========================================
-- 기존 정책 모두 삭제
DO $$ 
DECLARE
    r RECORD;
BEGIN
    FOR r IN (SELECT policyname FROM pg_policies WHERE tablename = 'profiles') LOOP
        EXECUTE 'DROP POLICY IF EXISTS "' || r.policyname || '" ON profiles';
    END LOOP;
END $$;

-- 새로운 정책 생성
CREATE POLICY "프로필 조회 허용" ON profiles
    FOR SELECT USING (true);

CREATE POLICY "본인 프로필 생성 허용" ON profiles
    FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "본인 프로필 수정 허용" ON profiles
    FOR UPDATE USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "본인 프로필 삭제 허용" ON profiles
    FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 8️⃣ updated_at 자동 갱신 트리거
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- posts 테이블 트리거
DROP TRIGGER IF EXISTS update_posts_updated_at ON posts;
CREATE TRIGGER update_posts_updated_at
    BEFORE UPDATE ON posts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- profiles 테이블 트리거
DROP TRIGGER IF EXISTS update_profiles_updated_at ON profiles;
CREATE TRIGGER update_profiles_updated_at
    BEFORE UPDATE ON profiles
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 9️⃣ Storage 버킷 생성 (프로필 이미지용)
-- ==========================================
-- avatars 버킷 생성 (이미 있으면 무시)
INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

-- avatars 버킷 정책: 누구나 읽기 가능
DROP POLICY IF EXISTS "Anyone can view avatars" ON storage.objects;
CREATE POLICY "Anyone can view avatars"
ON storage.objects FOR SELECT
USING (bucket_id = 'avatars');

-- avatars 버킷 정책: 인증된 사용자만 업로드 가능
DROP POLICY IF EXISTS "Authenticated users can upload avatars" ON storage.objects;
CREATE POLICY "Authenticated users can upload avatars"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'avatars' AND auth.role() = 'authenticated');

-- avatars 버킷 정책: 본인 파일만 삭제 가능
DROP POLICY IF EXISTS "Users can delete own avatars" ON storage.objects;
CREATE POLICY "Users can delete own avatars"
ON storage.objects FOR DELETE
USING (bucket_id = 'avatars' AND auth.uid()::text = (storage.foldername(name))[1]);

-- ==========================================
-- 🔟 스키마 캐시 강제 갱신 및 확인
-- ==========================================
-- 스키마 캐시 강제 갱신
NOTIFY pgrst, 'reload schema';

-- profiles 테이블 구조 확인
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns 
WHERE table_name = 'profiles' 
ORDER BY ordinal_position;

-- ==========================================
-- ✅ 설정 완료!
-- ==========================================
-- 
-- 📊 생성된 테이블:
-- - posts (게시물)
-- - comments (댓글)
-- - profiles (사용자 프로필: user_id, nickname, bio, avatar_url)
--
-- 🗂️ Storage 버킷:
-- - avatars (프로필 이미지 저장소)
--
-- 🔒 보안 정책 (RLS) 적용됨
-- ⚡ 자동 갱신 트리거 적용됨
-- 🔄 스키마 캐시 갱신됨
--
-- 💡 실행 후 profiles 테이블의 컬럼 목록이 표시됩니다.
--    user_id, nickname, bio, avatar_url 컬럼이 모두 포함되어 있는지 확인하세요!
--
-- ⚠️ 주의: 기존 profiles 테이블이 있었다면 데이터가 삭제되었습니다.
--
-- ==========================================
