-- ==========================================
-- 🎨 작품 댓글 시스템 설정
-- ==========================================
-- 
-- 📋 사용 방법:
-- 1. Supabase 대시보드 접속
-- 2. 왼쪽 메뉴에서 "SQL Editor" 클릭
-- 3. 이 파일의 전체 내용을 복사하여 붙여넣기
-- 4. "Run" 버튼 클릭
-- 
-- ==========================================

-- ==========================================
-- 1️⃣ artwork_comments 테이블 생성
-- ==========================================
CREATE TABLE IF NOT EXISTS artwork_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artwork_id BIGINT NOT NULL REFERENCES artworks(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content TEXT NOT NULL,
    author_nickname TEXT,
    author_email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 인덱스 생성 (빠른 조회)
CREATE INDEX IF NOT EXISTS artwork_comments_artwork_id_idx ON artwork_comments(artwork_id);
CREATE INDEX IF NOT EXISTS artwork_comments_user_id_idx ON artwork_comments(user_id);
CREATE INDEX IF NOT EXISTS artwork_comments_created_at_idx ON artwork_comments(created_at DESC);

-- ==========================================
-- 2️⃣ RLS (Row Level Security) 활성화
-- ==========================================
ALTER TABLE artwork_comments ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3️⃣ artwork_comments 보안 정책
-- ==========================================
-- 기존 정책 삭제
DROP POLICY IF EXISTS "Anyone can read artwork comments" ON artwork_comments;
DROP POLICY IF EXISTS "Authenticated users can create artwork comments" ON artwork_comments;
DROP POLICY IF EXISTS "Users can update own artwork comments" ON artwork_comments;
DROP POLICY IF EXISTS "Users can delete own artwork comments" ON artwork_comments;

-- 새로운 정책 생성
-- 누구나 댓글 조회 가능
CREATE POLICY "Anyone can read artwork comments" 
ON artwork_comments FOR SELECT 
USING (true);

-- 인증된 사용자만 댓글 작성 가능
CREATE POLICY "Authenticated users can create artwork comments" 
ON artwork_comments FOR INSERT 
WITH CHECK (auth.uid() = user_id);

-- 본인 댓글만 수정 가능
CREATE POLICY "Users can update own artwork comments" 
ON artwork_comments FOR UPDATE 
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

-- 본인 댓글만 삭제 가능
CREATE POLICY "Users can delete own artwork comments" 
ON artwork_comments FOR DELETE 
USING (auth.uid() = user_id);

-- ==========================================
-- 4️⃣ updated_at 자동 갱신 트리거
-- ==========================================
DROP TRIGGER IF EXISTS update_artwork_comments_updated_at ON artwork_comments;
CREATE TRIGGER update_artwork_comments_updated_at
    BEFORE UPDATE ON artwork_comments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 5️⃣ 댓글 수 집계 함수 (선택사항)
-- ==========================================
-- 특정 작품의 댓글 수를 반환하는 함수
CREATE OR REPLACE FUNCTION get_artwork_comment_count(artwork_bigint BIGINT)
RETURNS INTEGER AS $$
    SELECT COUNT(*)::INTEGER FROM artwork_comments WHERE artwork_id = artwork_bigint;
$$ LANGUAGE SQL STABLE;

-- ==========================================
-- ✅ 설정 완료!
-- ==========================================
-- 
-- 📊 생성된 테이블:
-- - artwork_comments (작품 댓글)
--
-- 🔒 보안 정책 (RLS) 적용됨
-- ⚡ 자동 갱신 트리거 적용됨
-- 📈 인덱스 생성됨
--
-- ==========================================
