-- ==========================================
-- 🎨 바이브코딩 작품 업로드 기능 설정
-- ==========================================
-- 
-- 📋 사용 방법:
-- 1. Supabase 대시보드 접속
-- 2. 왼쪽 메뉴에서 "SQL Editor" 클릭
-- 3. 이 파일의 전체 내용을 복사하여 붙여넣기
-- 4. "Run" 버튼 클릭
-- 
-- ==========================================

-- ==========================================
-- 1️⃣ artworks 테이블 생성 (작품 게시물)
-- ==========================================
CREATE TABLE IF NOT EXISTS artworks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    image_url TEXT, -- NULL 허용 (자유게시판 텍스트 전용 게시물 지원)
    author_nickname TEXT,
    author_email TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- user_id에 인덱스 생성 (빠른 조회)
CREATE INDEX IF NOT EXISTS artworks_user_id_idx ON artworks(user_id);

-- created_at에 인덱스 생성 (최신순 정렬)
CREATE INDEX IF NOT EXISTS artworks_created_at_idx ON artworks(created_at DESC);

-- ==========================================
-- 2️⃣ RLS (Row Level Security) 활성화
-- ==========================================
ALTER TABLE artworks ENABLE ROW LEVEL SECURITY;

-- ==========================================
-- 3️⃣ artworks 테이블 보안 정책
-- ==========================================
-- 기존 정책 삭제
DROP POLICY IF EXISTS "Anyone can read artworks" ON artworks;
DROP POLICY IF EXISTS "Authenticated users can create artworks" ON artworks;
DROP POLICY IF EXISTS "Users can update own artworks" ON artworks;
DROP POLICY IF EXISTS "Users can delete own artworks" ON artworks;

-- 누구나 작품 조회 가능
CREATE POLICY "Anyone can read artworks" ON artworks
    FOR SELECT USING (true);

-- 인증된 사용자만 작품 생성 가능
CREATE POLICY "Authenticated users can create artworks" ON artworks
    FOR INSERT WITH CHECK (auth.uid() = user_id);

-- 본인 작품만 수정 가능
CREATE POLICY "Users can update own artworks" ON artworks
    FOR UPDATE USING (auth.uid() = user_id)
    WITH CHECK (auth.uid() = user_id);

-- 본인 작품만 삭제 가능
CREATE POLICY "Users can delete own artworks" ON artworks
    FOR DELETE USING (auth.uid() = user_id);

-- ==========================================
-- 4️⃣ updated_at 자동 갱신 트리거
-- ==========================================
-- 트리거 함수는 이미 존재한다고 가정 (SETUP_DATABASE.sql에서 생성됨)
-- 없다면 아래 주석을 해제하여 생성
/*
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
*/

-- artworks 테이블 트리거
DROP TRIGGER IF EXISTS update_artworks_updated_at ON artworks;
CREATE TRIGGER update_artworks_updated_at
    BEFORE UPDATE ON artworks
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ==========================================
-- 5️⃣ Storage 버킷 생성 (작품 이미지용)
-- ==========================================
-- posts 버킷 생성 (이미 있으면 무시)
INSERT INTO storage.buckets (id, name, public)
VALUES ('posts', 'posts', true)
ON CONFLICT (id) DO NOTHING;

-- posts 버킷 정책: 누구나 읽기 가능
DROP POLICY IF EXISTS "Anyone can view posts" ON storage.objects;
CREATE POLICY "Anyone can view posts"
ON storage.objects FOR SELECT
USING (bucket_id = 'posts');

-- posts 버킷 정책: 인증된 사용자만 업로드 가능
DROP POLICY IF EXISTS "Authenticated users can upload posts" ON storage.objects;
CREATE POLICY "Authenticated users can upload posts"
ON storage.objects FOR INSERT
WITH CHECK (bucket_id = 'posts' AND auth.role() = 'authenticated');

-- posts 버킷 정책: 본인 파일만 업데이트 가능
DROP POLICY IF EXISTS "Users can update own posts" ON storage.objects;
CREATE POLICY "Users can update own posts"
ON storage.objects FOR UPDATE
USING (bucket_id = 'posts' AND auth.uid()::text = (storage.foldername(name))[1]);

-- posts 버킷 정책: 본인 파일만 삭제 가능
DROP POLICY IF EXISTS "Users can delete own posts" ON storage.objects;
CREATE POLICY "Users can delete own posts"
ON storage.objects FOR DELETE
USING (bucket_id = 'posts' AND auth.uid()::text = (storage.foldername(name))[1]);

-- ==========================================
-- 6️⃣ 스키마 캐시 강제 갱신
-- ==========================================
NOTIFY pgrst, 'reload schema';

-- artworks 테이블 구조 확인
SELECT column_name, data_type, is_nullable, column_default
FROM information_schema.columns 
WHERE table_name = 'artworks' 
ORDER BY ordinal_position;

-- ==========================================
-- ✅ 설정 완료!
-- ==========================================
-- 
-- 📊 생성된 테이블:
-- - artworks (작품 게시물: title, description, image_url [NULL 허용])
--
-- 🗂️ Storage 버킷:
-- - posts (작품 이미지 저장소)
--
-- 🔒 보안 정책 (RLS) 적용됨
-- ⚡ 자동 갱신 트리거 적용됨
-- 🔄 스키마 캐시 갱신됨
--
-- 💡 실행 후 artworks 테이블의 컬럼 목록이 표시됩니다.
--
-- ==========================================
